# Generated by Django 5.0.3 on 2024-04-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
