# Generated by Django 5.0.3 on 2024-04-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.TextField()),
                ('receiver_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveiver_message', to='users.profile')),
                ('sender_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='users.profile')),
            ],
        ),
    ]
